### ISSUE TITLE
Export CV to PDF

### ISSUE THREAD

**Issue by emmanuelperu** [germainlefebvre4/cvwonder#2]
It will be very nice to export CV in PDF format because some platform only accept this format.

**Describe the solution you'd like**
A new command export with one additional argument --format.

**Describe alternatives you've considered**
Maybe we can reuse the build command with the same previous addistional argument --format.

**Additional context**
The exported PDF could be stored in generated/pdf by default and a link could be added in the original html file.

**Comment by germainlefebvre4** [comment]
Nice idea.

I've start building a code base to start working on the extended `format` parameter.

**Comment by germainlefebvre4** [comment]
Generate the CV in PDF format with [Rod](https://github.com/go-rod/rod) library.

**How it works?**

CV Yaml format > Generate HTML > Generate PDF

Rod uses an embedded Chromium browser to save the rendered HTML output as PDF (as it would be saved as PDF like 'Print as PDF')
